spring:
  config:
    location: config/
  main:
    banner-mode: 'OFF'
  application:
    name: application
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tweets	
    username: tweets
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - classpath:migration/mysql
    out-of-order: true
